apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "config-man.fullname" . }}-backend
  labels:
    {{- include "config-man.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "config-man.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "config-man.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
              protocol: TCP
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: configman.config-man-postgres.credentials.postgresql.acid.zalan.do
                  key: password
            - name: DATABASE_URL
              value: "postgres://configman:$(DB_PASSWORD)@config-man-postgres:5432/config_man?sslmode=require"
            - name: CONFIG_MAN_HOST
              value: "0.0.0.0"
            - name: CONFIG_MAN_PORT
              value: "3000"
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.livenessProbe.httpGet.path }}
              port: {{ .Values.backend.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.readinessProbe.httpGet.path }}
              port: {{ .Values.backend.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
