apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config-man.fullname" . }}-nginx-conf
  labels:
    {{- include "config-man.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  default.conf: |
    server {
        listen 80;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://{{ include "config-man.fullname" . }}-backend:{{ .Values.backend.port }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
